apiVersion: v1
kind: Service
metadata:
  name: signup-svc
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: signup-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
