apiVersion: v1
kind: Service
metadata:
  name: id-validate-service-nodeport
spec:
  type: NodePort
  selector:
    app: id-validate-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
